service:
  name: tutor-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'ap-southeast-1'}

functions:
  main:
    handler: dist/lambda.handler
    environment:
      ENV: ${opt:stage, 'local'}
    events:
      - http:
          method: any
          path: /{any+}
